### PR TITLE
Change $function parameter type to "callable"

### PR DESCRIPTION
**Pull request by dcelasun**
This is a tiny fix for IDE type hints. Example: http://i.imgur.com/FdUZllR.png

### CODE REVIEW

**Comment by liebig** [comment]
Thanks for improving Cron, dcelasun!

**Comment by dcelasun** [comment]
Thanks! Can you also a tag a minor release so we can update? It's been a while since the last release anyway :)

**Comment by liebig** [comment]
Yes, of course. I will release 1.0.2 later this day.

**Comment by liebig** [comment]
Version 1.0.2 is released. Thank you for your support.

**Pull request merged**
