### PR TITLE
replace \Event::fire() calls with \Event::dispatch() fix #99

### LINKED ISSUE #99: doesn't work with Laravel 5.8
the `fire()` method in the event class has been removed in Laravel 5.8: https://laravel.com/docs/5.8/upgrade

> The fire Method
> Likelihood Of Impact: Low
> The fire method (which was deprecated in Laravel 5.4) of the Illuminate\Events\Dispatcher class has been removed. You should use the dispatch method instead.

### PR DESCRIPTION
**Pull request by larsbo**
replace deprecated and removed function to make the package Laravel 5.8 compatible.

### CODE REVIEW

**Comment by liebig** [comment]
Thank you very much Lars

**Comment by Mythli** [comment]
This actually breaks L4 support.

**Comment by larsbo** [comment]
That’s because you use `dev-master` in your composer. See https://github.com/liebig/cron/issues/99#issuecomment-559704697

**Comment by larsbo** [comment]
That’s because you use `dev-master` in your composer. See https://github.com/liebig/cron/issues/99#issuecomment-559704697

**Pull request merged**
